import { User, PracticePartner, LearningResource, ContentSuggestion, MediaItem } from './types';

export const mockUser: User = {
  userId: '1',
  farcasterId: 'user123',
  displayName: 'Alex Johnson',
  proficiencyLevel: 'Intermediate',
  interests: ['Travel', 'Food & Cooking', 'Music'],
  preferredPracticeTimes: ['Evening (18-24)'],
  subscriptionStatus: 'Free',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  bio: 'Learning Czech for travel and cultural exploration. Love discussing food and music!',
};

export const mockPartners: PracticePartner[] = [
  {
    partnerId: '1',
    userId: '2',
    displayName: 'Petra Novák',
    availability: ['Evening (18-24)', 'Morning (6-12)'],
    interests: ['Travel', 'Art & Culture', 'History'],
    proficiencyLevel: 'Advanced',
    bio: 'Native Czech speaker from Prague. Happy to help with pronunciation and cultural context!',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    isNative: true,
  },
  {
    partnerId: '2',
    userId: '3',
    displayName: 'Jan Svoboda',
    availability: ['Afternoon (12-18)', 'Evening (18-24)'],
    interests: ['Sports', 'Technology', 'Business'],
    proficiencyLevel: 'Advanced',
    bio: 'Software developer from Brno. Can help with technical vocabulary and business Czech.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    isNative: true,
  },
  {
    partnerId: '3',
    userId: '4',
    displayName: 'Maria Schmidt',
    availability: ['Morning (6-12)', 'Afternoon (12-18)'],
    interests: ['Books & Literature', 'Music', 'Food & Cooking'],
    proficiencyLevel: 'Intermediate',
    bio: 'Fellow learner from Germany. Let\'s practice together and share learning tips!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    isNative: false,
  },
];

export const mockResources: LearningResource[] = [
  {
    resourceId: '1',
    title: 'Czech Grammar Essentials',
    url: 'https://example.com/grammar',
    type: 'Grammar',
    category: 'Fundamentals',
    difficultyLevel: 'Beginner',
    description: 'Complete guide to Czech grammar basics including cases, verb conjugations, and sentence structure.',
    isPremium: false,
    createdAt: '2024-01-15',
  },
  {
    resourceId: '2',
    title: 'Advanced Czech Vocabulary Builder',
    url: 'https://example.com/vocab',
    type: 'Vocabulary',
    category: 'Advanced',
    difficultyLevel: 'Advanced',
    description: 'Expand your Czech vocabulary with 1000+ advanced words and phrases used in professional contexts.',
    isPremium: true,
    createdAt: '2024-01-20',
  },
  {
    resourceId: '3',
    title: 'Czech Pronunciation Guide',
    url: 'https://example.com/pronunciation',
    type: 'Video',
    category: 'Speaking',
    difficultyLevel: 'Beginner',
    description: 'Master Czech pronunciation with native speaker examples and practice exercises.',
    isPremium: false,
    createdAt: '2024-01-10',
  },
];

export const mockContent: ContentSuggestion[] = [
  {
    suggestionId: '1',
    userId: '1',
    contentTitle: 'Prague Castle Opens New Exhibition',
    contentType: 'News',
    url: 'https://example.com/news1',
    relevanceScore: 0.9,
    publishedAt: '2024-01-25',
    summary: 'Prague Castle unveils a new historical exhibition featuring medieval artifacts.',
  },
  {
    suggestionId: '2',
    userId: '1',
    contentTitle: 'Traditional Czech Cooking Blog',
    contentType: 'Blog',
    url: 'https://example.com/blog1',
    relevanceScore: 0.8,
    publishedAt: '2024-01-24',
    summary: 'Learn to cook authentic Czech dishes with step-by-step recipes and cultural insights.',
  },
  {
    suggestionId: '3',
    userId: '1',
    contentTitle: 'Czech Music History Podcast',
    contentType: 'Podcast',
    url: 'https://example.com/podcast1',
    relevanceScore: 0.7,
    publishedAt: '2024-01-23',
    summary: 'Explore the rich history of Czech classical and folk music traditions.',
  },
];

export const mockMedia: MediaItem[] = [
  {
    mediaId: '1',
    title: 'Pelíšky (Cosy Dens)',
    url: 'https://example.com/movie1',
    type: 'Film',
    description: 'Classic Czech comedy-drama about two neighboring families in 1960s Prague.',
    subtitleUrl: 'https://example.com/subtitles1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1489599735734-79b4169c4388?w=300&h=200&fit=crop',
    duration: '115 min',
    genre: ['Comedy', 'Drama'],
  },
  {
    mediaId: '2',
    title: 'Případy 1. oddělení',
    url: 'https://example.com/series1',
    type: 'Series',
    description: 'Popular Czech crime series following detectives solving cases in Prague.',
    subtitleUrl: 'https://example.com/subtitles2',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=300&h=200&fit=crop',
    duration: '45 min/episode',
    genre: ['Crime', 'Drama'],
  },
  {
    mediaId: '3',
    title: 'Czech Language Lessons',
    url: 'https://youtube.com/watch?v=example',
    type: 'YouTube',
    description: 'Comprehensive Czech language learning series with native speakers.',
    subtitleUrl: 'https://example.com/subtitles3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=300&h=200&fit=crop',
    duration: '20 min/video',
    genre: ['Educational'],
  },
];
